// Catálogo operativo PSB: adaptación ECODESA de 20 aspectos del instructivo.
// Cinco bloques y pesos redistribuidos proporcionalmente a 100%.

const PSB_PESOS = { edificacion: 11.1, equipos: 11.1, personal: 22.2, higienicos: 22.2, saneamiento: 33.3 };

const PSB_DETALLES = {
  edificacion_1: `El establecimiento está ubicado en un lugar alejado de focos de insalubridad como: basuras, agua estancada, sitios de anidamiento de plagas u otros que puedan contaminar el alimento; en todo caso la construcción debe ser resistente al medio ambiente y que impida el ingreso de plagas y animales domésticos. El establecimiento no debe ser usado como dormitorio, en caso que el servicio se preste en una edificación que también sea vivienda, debe estar separado físicamente de ésta. Las operaciones propias del establecimiento no deben poner en riesgo la salud y bienestar de la comunidad. La diferentes áreas del establecimiento deben permiter un flujo adecuado de materia prima, producto y personal.`,
  edificacion_2: `En las áreas de preparación de alimentos y en otras áreas que puedan afectar la higiene del proceso e inocuidad del producto, las Paredes, pisos y drenajes deben contar con:\n\nParedes y pisos: Sin grietas, rugosidades, asperezas o falta de continuidad que facilite la acumulación de suciedad y/o afecte su limpieza. En las áreas de preparación y almacenamiento de alimentos las uniones entre paredes, entre estas y con el piso deben ser redondeadas. Las superficies deben ser de color claro, impermeables, lavables y no absorbentes, esto es, que no permita el paso de ningún tipo de líquido y que fácilmente permita la eliminación de residuos. Los pisos deben comtar con la pendiente necesaria para efectos de drenaje.\n\nDrenajes: Debe contar con las tuberías y drenajes, debidamente protegidos por rejillas para la conducción y recolección de aguas residuales; en caso de que se cuente con drenajes al interior de cavas o cuartos fríos, estos deben contar con mecanismo de sellado que puedan ser removidos para facilitar las labores de limpieza y desinfección.`,
  edificacion_3: `En las áreas de preparación de alimentos y en otras áreas que puedan afectar la higiene del proceso e inocuidad del producto, los techos, ventilación, puertas e iluminación deben contar con las siguientes características:\n\nTechos: No tener cortes ni grietas que acumulen polvo o suciedad, que no favorezcan el crecimiento de hongos, ni que permita el ingreso de plagas al establecimiento. En caso de contar con falsos techos, estos de deben ser de material impermeable, resistente, liso y con acceso a la cámara superior para labores de limpieza, desinfección y desinsectación.\n\nVentilación: Las Ventanas y aberturas no deben tener deterioro, como grietas. Aquellas que lo requieran deberán contar con una malla de facil limpieza y que evite el ingreso plagas. El flujo de aire debe ser unidireccional (De una zona limpia a una sucia). La ventilación debe facilitar la remoción del calor y no debe generar condensación de vapores y acúmulo de polvo. Las estructuras elevadas como sistemas de extracción y/o extractores de aire, deben ser de fácil limpiezay debe encontrarse en buen estado de mantenimiento para evitar la caída de materias extrañas.\n\nPuertas: Deben ser resistentes, de superficie lisa y no absorbente, su diseño debe impedir el ingreso de plagas al establecimiento.\n\nIluminación: La iluminación puede ser natural o artificial, las lámparas deben encontrarse en buen estado de mantenimiento, ser de fácil limpieza y estar protegidas para evitar la caída de partículas extrañas sobre las superficies que entran en contacto con el alimento, sobre el alimento y sobre los manipuladores.`,
  edificacion_4: `El establecimiento dispone de servicios sanitarios en material higiénico sanitario, vestidores y casilleros en cantidad suficiente con respecto a la cantidad de personal que labora en él, independientes para cada sexo y separados de las áreas de elaboración. En caso de no contar con más de seis (6) manipuladores, dispone de un baño mixto.\n\nDebe contar con servicios sanitarios suficientes para el público separados por sexo, si el establecimiento se encuentra ubicado en un centro comercial el público podrá hacer uso de los baños del centro comercial. Los servicios sanitarios se deben encontrar en funcionamiento, ser mantenidos limpios y estar dotados de los implementos requeridos para la higiene personal como: Papel higiénico, dispensador con jabón desinfectante, implementos desechables o equipos automáticos para el secado de manos y papeleras de accionamiento no manual.\n\nEn las áreas de preparación de alimentos o cercano a éstas se debe contar con lavamanos de accionamiento no manual, dotados con dispensador que contenga jabón desinfectante, implementos desechables o equipos automáticos para secado de manos para la higiene del personal manipulador de alimentos. Los lavamanos no deben ser usados para fines diferentes.\n\nDeben instalarse avisos que indiquen al personal manipulador la necesidad del lavado de manos luego de usar los servicios sanitarios, después de cualquier cambio de actividad y antes de iniciar las labores diarias.`,
  equipos_1: `Debe contar con los equipos y utensilios de fácil limpieza y desinfección, en cantidad necesaria para desarrollar las actividades propias del establecimiento. Estos deben estar diseñados, construidos, instalados y mantenidos de forma que se evita la contaminación del alimento. Los materiales en que esten construidos los equipos y utensilios deben ser resistentes al uso y a la corrosión, así como al contacto con productos empleados de limpieza y desinfección.\n\nEl establecimiento debe contar con instrumentos o accesorios que permitan la medición de las temperaturas, durante la cocción, refrigeración y congelación de alimentos o materias primas.`,
  equipos_2: `Las superficies que tengan contacto directo con el alimento deben cumplir con lo establecido en las Resoluciones 683, 4142, 4143 de 2012 y 834, 835 de 2013 o las normas que las modifiquen, adicionen o sustituyan.\n\nLas superficies de los equipos y utensilios que estarán en contacto directo con los alimentos deben ser de acabado liso, no poroso, no absorbente y no tener defectos, grietas o espacios donde puedan acumularse partículas de alimentos, además, deben ser de fácil acceso para realizar las actividades de limpieza y desinfección necesarias; Por otra parte, las superficies que entren en contacto directo con el alimento y que no sean de fácil acceso, deben ser desmontables para garantizar procesos de limpieza y desinfección. Estas superficies no deben desprender residuos o cuerpos extraños que puedan adherirse al alimento y afectar su inocuidad. Finalmente. las superficies donde se corten o fraccionen los alimentos deben ser de material sanitario y mantenerse en buen estado de conservación.\n\nEn caso de usar utensilios en material desechable, estos deben ser de primer y único uso.`,
  personal_1: `El establecimiento debe implementar las medidas preventivas y correctivas necesarias, como cambio de actividad o envío del manipulador a reconocimiento médico para ser evaluado, con el fin de evitar que un manipulador de alimentos que padece o es portador de una enfermedad susceptible de transmitirse por los alimentos, o tenga heridas infectadas, irritaciones cutáneas o diarrea, trabaje en las zonas o áreas de manipulación de alimentos con probabilidad de contaminar las materias primas, alimentos en proceso, alimentos terminados, envases de alimentos o material de envase o embalaje, superficies de equipos y utensilios con microorganismos patógenos.`,
  personal_2: `El establecimiento debe contar con los certificados médicos de los manipuladores, en los cuales consta la aptitud de éstos para manipular alimentos. Estos certificados deben tener una vigencia máxima de un año a partir de su realización.\n\nSegún la valoración del médico al manipulador, en caso de ser necesario se debe contar con resultados de laboratorio clínico u otros que sean necesarios para establecer la aptitud del manipulador en caso de que se sospeche de enfermedad trasmisible a los alimentos.\n\nEn caso que el médico ordenase un tratamiento al manipulador, el establecimiento debe contar con certificado en el cual conste la aptitud para la manipulación de alimentos una vez finalizado el tratamiento.`,
  personal_3: `Higiene personal: Todos los manipuladores de alimentos deben cumplir con las buenas prácticas higiénicas en sus sitios de trabajo, a fin de evitar la contaminación de los alimentos, superficies de contacto, materiales de envase y embalaje. Las uñas se deben mantener cortas, limpias y sin esmalte. Los manipuladores de alimentos no deben consumir alimentos o bebidas, ni fumar ni escupir en las áreas donde se manipulen alimentos. Las personas encargadas de la preparación o el servido de los alimentos, no deben manipular dinero simultáneamente. El servido los alimentos se debe realizar con utensilios de material sanitario y en ningún momento las manos del manipulador deben tener contacto con el alimento..\n\nDotación: El establecimiento debera entregar la dotación y vestimenta de trabajo al personal manipulador acorde con la actividad que realice. El Cabellos debe estar cubierto. Cuando sea necesario se deberá usar tapabocas (Dependiendo del riesgo de contaminación del alimento). La vestimenta debe ser de color claro, con cierre, cremallera o broche (no botones). El calzado debe ser cerrado, de material resistente e impermeable, según la actividad que realiza. El manipulador de alimentos no debe salir ni ingresar al establecimiento con la vestimenta de trabajo durante la jornada laboral. Previo al inicio de sus actividades, se deben retirar todos los objetos que puedan caer en los alimentos, equipos o utensilios, como joyas, relojes u otros accesorios. De usarse guantes para manipular los alimentos, estos deben ser de material impermeable, mantenerse limpios y en buen estado y ser sometidos al mismo cuidado higiénico de las manos (lavado y desinfección).\n\nLavado de manos: Antes de iniciar sus labores, después de retirarse del área de trabajo y en cualquier ocasión donde las manos se puedan ensuciar o contaminar, los manipuladores de alimentos se las deben lavar con agua y jabón desinfectante.`,
  personal_4: `El establecimiento debe contar con un plan de capacitación, acorde con la actividad que realiza. para el personal manipulador de alimentos para que se implemente de manera continua y permanente desde el momento de la contratación del manipulador y luego ser reforzado mediante charlas, cursos u otros medios efectivos de actualización Esta capacitación estará bajo la responsabilidad de la empresa y podrá ser efectuada por esta, por personas naturales o jurídicas contratadas y por las autoridades sanitarias. Cuando el plan de capacitación se realice a través de personas naturales o jurídicas diferentes a la empresa, estas deben demostrar su idoneidad técnica y científica y su formación y experiencia específica en las áreas de higiene de los alimentos, Buenas Prácticas de Manufactura y sistemas preventivos de aseguramiento de la inocuidad.\n\nEl plan debe tener una duración de por lo menos 10 horas anuales y contener temas relacionados con buenas prácticas de manufactura y prácticas higiénicas (Manipulación higiénica de los alimentos, Higiene personal, Higiene de las instalaciones, Control de plagas, prevención de la contaminación cruzada, control de proveedores, control de temperatura, Almacenamiento y transporte de alimentos, entre otras). Contener al menos los siguientes aspectos: Metodología, duración, responsables, cronograma, temas a tratar y evaluación del impacto. Como evidencia del cumplimiento del plan se debe contar con registros de asistencia y evaluación de cada uno de los participantes.\n\nLos manipuladores de alimentos deben comprender los puntos del proceso que esten bajo su responsabilidad y las acciones correctivas a tomar cuando existan desviaciones. Lo anterior lo evidenciará el inspector a través de entrevistas a manipuladores y/o a traves de la observación.`,
  higienicos_1: `Durante la recepción de las materias primas e insumos (incluido el hielo) se debe evitar su contaminación, alteración o daños físicos y de requerirse se deberán encontrar debidamente rotuladas según la normatividad sanitaria vigente. El establecimiento debe contar con los documentos que soporten el origen de las materias primas. Tanto en la recepción, como previo al uso se deben inspeccionar las materias primas e insumos en cuanto a características organolépticas, temperaturas, condiciones de envase, entre otros, para garantizar su calidad e inocuidad.\n\nLas materias primas lo requieran, deben ser lavadas con agua potable y desinfectadas previo al uso. Aquellas conservadas mediante congelación, deben ser descongeladas gradualmente previo al uso y no ser recongeladas.\n\nLos productos de la pesca deben ser descargados y almacenados de manera rapida evitando al perdida de temperatura y contaminación de estos.`,
  higienicos_2: `Los procedimientos como lavar, pelar, cortar, clasificar, desmenuzar, extraer, batir, secar, entre otros, se deben realizar de manera tal que se protejan los alimentos y las materias primas de la contaminación. Durante las etapas de refrigeración, congelación y cocción se debe garantizar que los tiempos de espera y las variaciones de temperatura no alteren o contaminen los alimentos.\n\nEl establecimiento debe prevenir la contaminación de los alimentos precocidos o aquellos que esten listos para ser servidos (crudos o cocinados), por contacto directo o indirecto con materias primas crudas que no hayan sido lavadas y desinfectadas. En caso de emplear hielo que entre en contacto directo con los alimentos, este debe ser elaborado con agua potable.\n\nLos equipos y utensilios que entren en contacto con materias primas o elementos contaminados, se deben lavar y desinfectar antes de ser usados nuevamente.`,
  higienicos_3: `Los alimentos que requieran cocción deben alcanzar una temperatura mayor de 60°C. La cocción de alimentos por contacto directo con la llama no debe producir contaminación del alimento.\n\nLos alimentos que requieran refrigeración y/o congelación se deben mantener a las temperaturas exigidas por la normatividad sanitaria vigente según el tipo de producto. Una vez que se descongele un alimento, estos no deben ser recongelados o refrigerados.\n\nCuando se requiera esperar, entre una actividad y otra, el alimento se debe mantener protegido garantizando que se conserve a temperaturas mayores a 60°C o no mayores de 4°C +/- 2, según el tipo de alimento.`,
  higienicos_4: `Los envases que entren en contacto con el alimento se deben almacenar en un sitio exclusivo para este fin en condiciones higiénicas y protegidos de manera que se evite su contaminación.\n\nLas materias primas e insumos que requieran ser almacenados, antes de ser usados para la preparación, se deben almacenr en sitios que aseguren su protección de la contaminación y alteración. No se deben almacenar sustancias peligrosas en la cocina, en áreas de preparación de alimentos, ni en áreas de almacenamiento de las materias primas.`,
  saneamiento_1: `El establecimiento debe disponer de suministro de agua potable en cantidad suficiente para las actividades que se realicen, así como para las operaciones de limpieza y desinfección.\n\nEn caso de contar con un sistema de almacenamiento de agua, éste debe ser de fácil acceso, garantizar la potabilidad del agua, estar construido con materiales sanitarios resistentes, no porosos, impermeables, no absorbentes y con acabados libres de grietas o defectos que dificulten su limpieza y desinfección.`,
  saneamiento_2: `El establecimiento debe contar con los sistemas de desagüe que permita la evacuación rápida y eficiente de los residuos líquidos, evitando el acúmulo de éstos, la contaminación de los alimentos y las superficies que entren en contacto con éstos últimos. El sistema debe garantizar que no exista devolución de las aguas servidas. La presencia de olores desagradables en el establecimiento pueden indicar un mal funcionamiento del sistema de desagüe.`,
  saneamiento_3: `El establecimiento debe tener implementadas las medidas necesarias para la disposición adecuada y el retiro oportuno de los residuos sólidos, de manera que no se acumulen en las áreas de preparación, almacenamiento y servido de los alimentos (Incluye sobras, descartes, envases, material de embalaje, entre otros). Debe cuenta con los recipientes para la disposición temporal de los residuos sólidos, de material sanitario debidamente tapados y se deben encontrar alejados del lugar donde se preparan, almacenan o se sirven los alimentos.\n\nLos residuos sólidos se deben disponer de forma que se impide el acceso y proliferación de plagas.`,
  saneamiento_4: `En el establecimiento no se deben hallar evidencia la presencia de plagas o daños ocasionados por éstas y se debe contar con medidas de control integral de tipo preventivo, para evitar su aparición.`,
  saneamiento_5: `El establecimiento debe implementar medidas para evitar la contaminación de equipos y utensilios después que éstos se limpien y desinfecten. Los productos químicos para la limpieza y desinfección se deben almacenar en sitios diferentes a las áreas de almacenamiento, preparación y servido de alimentos, y estar debidamente rotulados e identificados. Los implementos empleados en las labores de limpieza y desinfección se deben mantener en buen estado y no deben representar riesgo de contaminación para el alimento, ni para las áreas, equipos y utensilios en contacto estos. Las labores de limpieza y desinfección de los implementos de aseo se deben realizar en un sitio diferente a las áreas de manipulación de alimentos.\n\nLos agentes químicos utilizados para las operaciones de limpieza y desinfección deben ser preparados de acuerdo con las indicaciones y en las concentraciones definidas por el fabricante o proveedor.`,
  saneamiento_6: `El establecimientodebe contar con un plan de saneamiento escrito, acorde con su actividad, el cual debe contener como mínimo los siguientes programas:\na. Limpieza y desinfección: Debe incluir las sustancias empleadas, concentración y forma de uso;\nb. Desechos sólidos: Debe incluir el procedimiento de recolección, conducción, manejo, almacenamiento interno, clasificación y disposición final;\nc. Control de plagas: Debe incluir las diferentes medidas de control preventivo necesarias para el establecimiento;\nd. Abastecimiento o suministro de agua potable: Debe incluir las fuentes de captación y los tratamientos realizados para garantizar la potabilidad del agua.\n\nEl establecimiento debe contar con los registros que soportan el cumplimiento del plan de saneamiento, incluidos aquellos que permitan evidenciar que los sistemas de almacenamiento de agua potable sean lavados y desinfectados de acuerdo a lo establecido en la normatividad sanitaria vigente en la materia.`,
};

function _aspecto(id, texto, norma) {
  return { id, texto, norma, detalle: PSB_DETALLES[id] || '', subtitulo: '', criterio: null, evaluacion: null, hallazgo: '', accion: '', obs: '', obs_editada: false, recomendaciones: '', cumple_requerimientos: null, estado: null, fotografias: [], hallazgo_critico: false, plazo: null };
}

function getPSBAspectoDetalle(id) { return PSB_DETALLES[id] || ''; }

function getPSBPrograms() {
  return [
    { id: 'edificacion', codigo: 'EDI', nombre: 'Edificación e Instalaciones', peso: PSB_PESOS.edificacion, peso_critico: true, aspectos: [
      _aspecto('edificacion_1', 'Localización y diseño.', 'Resolución 2674/2013, arts. 5–7 y 32–33.'),
      _aspecto('edificacion_2', 'Condiciones de pisos y paredes.', 'Resolución 2674/2013, art. 7 y art. 33.'),
      _aspecto('edificacion_3', 'Techos, iluminación y ventilación.', 'Resolución 2674/2013, art. 7 y art. 33.'),
      _aspecto('edificacion_4', 'Instalaciones sanitarias.', 'Resolución 2674/2013, arts. 6, 32 y 33.'),
    ] },
    { id: 'equipos', codigo: 'EQU', nombre: 'Equipos y Utensilios', peso: PSB_PESOS.equipos, peso_critico: true, aspectos: [
      _aspecto('equipos_1', 'Condiciones de equipos y utensilios.', 'Resolución 2674/2013, arts. 8–10 y 34.'),
      _aspecto('equipos_2', 'Superficies de contacto con el alimento.', 'Resolución 2674/2013, arts. 8–10, 34 y 35.'),
    ] },
    { id: 'personal', codigo: 'PER', nombre: 'Personal Manipulador de Alimentos', peso: PSB_PESOS.personal, peso_critico: true, aspectos: [
      _aspecto('personal_1', 'Estado de salud (signos y lesiones).', 'Resolución 2674/2013, arts. 11 y 14.'),
      _aspecto('personal_2', 'Reconocimiento médico.', 'Resolución 2674/2013, art. 11.'),
      _aspecto('personal_3', 'Prácticas higiénicas.', 'Resolución 2674/2013, arts. 14, 35 y 36.'),
      _aspecto('personal_4', 'Educación y capacitación.', 'Resolución 2674/2013, arts. 12, 13 y 36.'),
    ] },
    { id: 'higienicos', codigo: 'HIG', nombre: 'Requisitos Higiénicos', peso: PSB_PESOS.higienicos, peso_critico: true, aspectos: [
      _aspecto('higienicos_1', 'Control de materias primas e insumos.', 'Resolución 2674/2013, arts. 16 y 35.'),
      _aspecto('higienicos_2', 'Prevención de contaminación cruzada.', 'Resolución 2674/2013, arts. 16, 18, 20 y 35.'),
      _aspecto('higienicos_3', 'Manejo de temperaturas.', 'Ley 9/1979 y Resolución 2674/2013, art. 18.'),
      _aspecto('higienicos_4', 'Condiciones de almacenamiento.', 'Resolución 2674/2013, arts. 16 y 33.'),
    ] },
    { id: 'saneamiento', codigo: 'SAN', nombre: 'Saneamiento', peso: PSB_PESOS.saneamiento, peso_critico: true, aspectos: [
      _aspecto('saneamiento_1', 'Suministro y calidad de agua potable.', 'Resolución 2674/2013, arts. 6, 26 y 32. Decreto 1575/2007 y Resolución 2115/2007, cuando aplique.'),
      _aspecto('saneamiento_2', 'Manejo de residuos líquidos.', 'Resolución 2674/2013, arts. 6 y 32.'),
      _aspecto('saneamiento_3', 'Manejo de residuos sólidos.', 'Resolución 2674/2013, arts. 6, 18 y 33.'),
      _aspecto('saneamiento_4', 'Control integral de plagas.', 'Resolución 2674/2013, art. 26.'),
      _aspecto('saneamiento_5', 'Limpieza y desinfección de áreas, equipos y utensilios.', 'Resolución 2674/2013, arts. 6 y 26.'),
      _aspecto('saneamiento_6', 'Soportes documentales de saneamiento.', 'Resolución 2674/2013, art. 26.'),
    ] },
  ];
}

function crearInspeccion(establecimiento, profesional) {
  const ahora = new Date();
  const numeroActa = 'PSB-' + ahora.getFullYear() + '-' + String(ahora.getTime()).slice(-4);
  return { id: 'psb-' + ahora.getTime() + '-' + Math.random().toString(36).slice(2, 8), fase_phva: 'P', establecimiento: { ...establecimiento }, inspeccion: { inspector: profesional || '', fecha: ahora.toISOString().split('T')[0], hora_inicio: ahora.toTimeString().slice(0, 5), hora_fin: null, numero_acta: numeroActa }, numero_acta: numeroActa, programas: getPSBPrograms(), estado_general: null, hallazgos_criticos: [], score: { A: 0, I: 0, NA: 0, total: 0, pct_cumplimiento: 0 }, creado_en: ahora.toISOString(), actualizado_en: ahora.toISOString(), version_app: '2.0.0' };
}
